spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    clean-disabled: false

logging:
  level:
    root: INFO
    com.winereviewer.api: DEBUG
    org.testcontainers: INFO
