name: CI - API
on:
  push:
    paths:
      - "services/api/**"
      - ".github/workflows/ci-api.yml"
  pull_request:
    paths:
      - "services/api/**"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build & Test (API)
        run: |
          cd services/api
          ./mvnw -q -DskipTests=false verify
