name: Release
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: "SemVer (ex.: 0.1.0)"
        required: true
jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
      - name: Generate GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          body: "Release v${{ github.event.inputs.version }} - See CHANGELOG.md"
